<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Lab_Documentacion_1</RootNamespace>
    <AssemblyName>Lab_Documentacion_1</AssemblyName>
    <StartupObject>Lab_Documentacion_1.Program</StartupObject>
    <MyType>Windows</MyType>
    <OptionExplicit>On</OptionExplicit>
    <OptionStrict>On</OptionStrict>
    <OptionInfer>On</OptionInfer>
    <OptionCompare>Binary</OptionCompare>
  </PropertyGroup>

</Project>
